# lintr configuration for cindexdecomp (R-format config, lintr >= 3.1).
#
# Run as:
#   pkgload::load_all(); lintr::lint_package()
#
# load_all() first: object_usage_linter cannot resolve the package's internal
# @noRd helpers across files unless the namespace is loaded, and otherwise
# reports a spurious "no visible global function definition" for every one of
# them (decomp_from_pairs, boot_percentile, validate_weights_and_orientation).
linters <- lintr::linters_with_defaults(
  # The package implements a published estimator and deliberately mirrors its
  # notation: C_ee, C_ec, C_global, W_ee, S_ec, N_ee, G(t). Renaming these to
  # snake_case would sever the link between the code and the maths in the
  # vignette and the reference docs. S3 methods additionally inherit
  # non-snake argument names from their generics (as.data.frame's row.names).
  object_name_linter = NULL,
  # styler::style_pkg() is the formatter of record here, and styler and
  # lintr disagree by two spaces on how a wrapped `if (a || \n b)` condition
  # is indented. No hanging_indent_style setting reconciles them, so styler
  # owns indentation and this linter stands down.
  indentation_linter = NULL,
  # validate_weights_and_orientation() is 32 characters and says exactly what
  # it does; 30 is too tight for a package with compound validator names.
  object_length_linter = lintr::object_length_linter(length = 40L),
  line_length_linter = lintr::line_length_linter(length = 80L)
)

exclusions <- list(
  # Boilerplate generated by usethis; not ours to style.
  "tests/testthat.R",
  # testthat descriptions are full sentences that state what the test pins
  # down. Squeezing them under 80 columns would cost more in legibility than
  # the wrapping buys, so the length rule stands down inside the suite only
  # -- every other linter still applies here, and R/ is still held to 80.
  "tests/testthat" = list(line_length_linter = Inf)
)
